modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
issueTrackerURL="https://github.com/SodiumZH/Days-with-Monster-Girls"
[[mods]] #mandatory
modId="dwmg" #mandatory
version="0.1.0-snapshot.4" #mandatory
displayName="Days with Monster Girls" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/befriendmobs-days-with-monster-girls" 
#logoFile="examplemod.png" #optional
credits="SodiumZH" #optional
authors="SodiumZH" #optional
description='''Enjoy your Minecraft days with monster girls!'''

[[dependencies.dwmg]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.dwmg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.dwmg]]
    modId="hmag"
    mandatory=true
    versionRange="[6.1.0, 7.0)"
    ordering="NONE"
    side="BOTH"
