
[entity]
	enableEnderExecutorReduceDamage = true
	enableEnderExecutorBeamAttack = true
	lichAttackBabyTurtles = true
	lichSummonVex = true
	ogreAttackVillagers = true
	ogreAttackBabyTurtles = true
	enableOgreDestroyBlocks = true
	spiderNestSummonCaveSpider = true
	enableMeltyMonsterSetFire = true
	kashaAttackChickens = true
	kashaAttackBabyHoglins = true
	kashaAttackVillagers = true
	kashaAttackBabyTurtles = true
	enableJackFrostFreezesWater = true
	enableJackFrostRegen = true
	alrauneAttackVillagers = true
	enableAlrauneRegen = true
	redcapAttackVillagers = true
	redcapAttackBabyTurtles = true
	enableSlimeGirlRegen = true
	magicalSlimeSpawnsOnSlimeGirlDeath = true
	monolithAttackGolems = true
	monolithAttackVillagers = true
	monolithAttackIllagers = true
	crimsonSlaughtererAttackAnimals = true
	crimsonSlaughtererAttackVillagers = true
	dyssomniaSummonPhantom = true
	snowCanineAttackSheep = true
	snowCanineAttackRabbits = true
	snowCanineAttackBabyTurtles = true
	savagefangAttackAnimals = true
	savagefangAttackVillagers = true
	savagefangAttackIllagers = true
	savagefangAttackDamagedMobs = true
	necroticReaperAttackVillagers = true
	necroticReaperAttackBabyTurtles = true
	enableGlaryadRegen = true

	[entity.spawn]
		spawnBiomeBlacklist = ["minecraft:mushroom_fields", "biomesoplenty:rainbow_hills", "biomesoplenty:crystalline_chasm", "cinderscapes:luminous_grove", "infernalexp:glowstone_canyon"]
		spawnDimentionBlacklist = [""]
		mobReplaceBiomeBlacklist = [""]
		mobReplaceDimentionBlacklist = [""]
		spawnOverworldBiomeWhitelist = [""]
		spawnNetherBiomeWhitelist = [""]
		spawnEndBiomeWhitelist = [""]

		[entity.spawn.replaceChance]
			#Range: 0.0 ~ 1.0
			zombieGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			huskGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			drownedGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			skeletonGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			witherSkeletonGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			strayGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			creeperGirlReplaceChance = 0.15
			#Range: 0.0 ~ 1.0
			enderExecutorReplaceChance = 0.03125

		[entity.spawn.weight]
			#Range: > 0
			ghostSpawnWeight = 25
			#Range: > 0
			witherGhostSpawnWeight = 12
			#Range: > 0
			witherGhostSpawnWeightInSoulSandValley = 8
			#Range: > 0
			witherGhostSpawnWeightInBasaltDeltas = 5
			#Range: > 0
			koboldSpawnWeight = 20
			#Range: > 0
			lichSpawnWeight = 8
			#Range: > 0
			ogreSpawnWeight = 8
			#Range: > 0
			spiderNestSpawnWeight = 8
			#Range: > 0
			meltyMonsterSpawnWeight = 15
			#Range: > 0
			meltyMonsterSpawnWeightInNether = 2
			#Range: > 0
			meltyMonsterSpawnWeightInEnd = 0
			#Range: > 0
			cursedDollSpawnWeight = 15
			#Range: > 0
			jackFrostSpawnWeight = 10
			#Range: > 0
			hornetSpawnWeight = 10
			#Range: > 0
			dullahanSpawnWeight = 10
			#Range: > 0
			bansheeSpawnWeight = 15
			#Range: > 0
			alrauneSpawnWeight = 10
			#Range: > 0
			catoblepasSpawnWeight = 15
			#Range: > 0
			scorpionSpawnWeight = 15
			#Range: > 0
			kashaSpawnWeight = 5
			#Range: > 0
			kashaSpawnWeightInSoulSandValley = 3
			#Range: > 0
			kashaSpawnWeightInBasaltDeltas = 2
			#Range: > 0
			doguSpawnWeight = 10
			#Range: > 0
			ghastlySeekerSpawnWeight = 7
			#Range: > 0
			ghastlySeekerSpawnWeightInSoulSandValley = 4
			#Range: > 0
			ghastlySeekerSpawnWeightInBasaltDeltas = 2
			#Range: > 0
			redcapSpawnWeight = 15
			#Range: > 0
			slimeGirlSpawnWeight = 10
			#Range: > 0
			monolithSpawnWeight = 3
			#Range: > 0
			monolithSpawnWeightInEndCity = 40
			#Range: > 0
			crimsonSlaughtererSpawnWeight = 2
			#Range: > 0
			dyssomniaSpawnWeight = 5
			#Range: > 0
			snowCanineSpawnWeight = 15
			#Range: > 0
			harpySpawnWeight = 15
			#Range: > 0
			savagefangSpawnWeightInSwamp = 10
			#Range: > 0
			savagefangSpawnWeightInJungle = 20
			#Range: > 0
			fortressKeeperSpawnWeightInNetherFortress = 5
			#Range: > 0
			necroticReaperSpawnWeight = 8
			#Range: > 0
			dodomekiSpawnWeight = 15
			#Range: > 0
			impSpawnWeight = 5
			#Range: > 0
			impSpawnWeightInCrimsonForest = 2
			#Range: > 0
			impSpawnWeightInBasaltDeltas = 2
			#Range: > 0
			glaryadSpawnWeight = 50

		[entity.spawn.chance]
			#Range: 0.0 ~ 1.0
			ghastlySeekerSpawnChance = 0.05
			#Range: 0.0 ~ 1.0
			crimsonSlaughtererSpawnChance = 0.375
			#Range: 0.0 ~ 1.0
			savagefangSpawnChance = 0.8

		[entity.spawn.height]
			#Range: -64 ~ 320
			surfaceMobSpawnMinHeight = 64
			#Range: -64 ~ 320
			koboldSpawnMaxHeight = 31
			#Range: -64 ~ 320
			lichSpawnMaxHeight = -1
			#Range: -64 ~ 320
			ogreSpawnMaxHeight = -1
			#Range: -64 ~ 320
			spiderNestSpawnMaxHeight = -1
			#Range: -64 ~ 320
			necroticReaperSpawnMaxHeight = -1

[enchantment]
	#Range: 1 ~ 10
	healthBoostMaxLevel = 5
	healthBoostIsTreasure = true
	healthBoostIsTradeable = true
	healthBoostIsDiscoverable = true
	#Range: 1 ~ 10
	waterAspectMaxLevel = 5
	waterAspectIsTreasure = false
	waterAspectIsTradeable = true
	waterAspectIsDiscoverable = true
	#Range: 1 ~ 10
	antiAirMaxLevel = 5
	antiAirIsTreasure = false
	antiAirIsTradeable = true
	antiAirIsDiscoverable = true

[potion]
	enableKoboldPotionBrewingRecipes = true
	enableHealingIIIPotionBrewingRecipes = true
	enableHarmingIIIPotionBrewingRecipes = true
	enableOgrePotionBrewingRecipes = true
	enableVoracityPotionBrewingRecipes = true
	enableEnderRagePotionBrewingRecipes = true
	enableCombustionPotionBrewingRecipes = true
	enableSlownessPotionBrewingRecipes = true
	enableInvisibilityPotionBrewingRecipes = true
	enableRegenerationIIIPotionBrewingRecipes = true
	enableBlastingBottleBrewingRecipe = true
	enableLightningBottleBrewingRecipe = true

[world]
	additionalChestLoots = true
	additionalVillagerTrades = true
	additionalWandererTrades = true

[item]
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel0 = 1800
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel1 = 1800
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel2 = 1800
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel3 = 1600
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel4 = 1400
	#Range: 0 ~ 240000
	insomuniaFruitCooldownLevel5 = 1200

